spring:
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/TEST
    username: tuser
    password: tpassword
    driverClassName: oracle.jdbc.driver.OracleDriver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
#  jpa:
#    showSql: true
#    hibernate:
#      ddlAuto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect
