spring:
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
  datasource:
    url: jdbc:oracle:thin:@//your-local-ip-address:1521/TEST
    username: tuser
    password: tpassword
    driverClassName: oracle.jdbc.driver.OracleDriver